# Generated by Django 3.1.7 on 2021-04-25 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_tbcell_tbkpi_tbmrodata_tbprb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcell',
            name='azimuth',
            field=models.FloatField(db_column='AZIMUTH', default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbcell',
            name='totletilt',
            field=models.FloatField(db_column='TOTLETILT', default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='rpc_succrate',
            field=models.FloatField(db_column='RPC_SUCCRATE', null=True),
        ),
        migrations.AlterField(
            model_name='tbmrodata',
            name='interferingsector',
            field=models.CharField(db_column='InterferingSector', default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbmrodata',
            name='servingsector',
            field=models.CharField(db_column='ServingSector', default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbmrodata',
            name='timestamp',
            field=models.CharField(db_column='TimeStamp', default=datetime.datetime(2021, 4, 25, 11, 19, 41, 378116), max_length=30),
            preserve_default=False,
        ),
    ]
