# Generated by Django 3.1.7 on 2021-04-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210425_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('Variable_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('Value', models.IntegerField()),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='tbmrodata',
        #     name='id',
        # ),
        migrations.AlterField(
            model_name='tbkpi',
            name='ay',
            field=models.FloatField(blank=True, db_column='AY', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='date',
            field=models.DateField(blank=True, db_column='Date', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enb_in_succ',
            field=models.IntegerField(blank=True, db_column='ENB_IN_SUCC', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='eno_in_request',
            field=models.IntegerField(blank=True, db_column='ENO_IN_REQUEST', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_diff_succrate',
            field=models.FloatField(blank=True, db_column='ENODEB_DIFF_SUCCRATE', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_erab_ex',
            field=models.IntegerField(blank=True, db_column='ENODEB_ERAB_EX', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_in_diff_att',
            field=models.IntegerField(blank=True, db_column='ENODEB_IN_DIFF_ATT', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_in_diff_succ',
            field=models.IntegerField(blank=True, db_column='ENODEB_IN_DIFF_SUCC', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_in_same_att',
            field=models.IntegerField(blank=True, db_column='ENODEB_IN_SAME_ATT', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_in_same_succ',
            field=models.IntegerField(blank=True, db_column='ENODEB_IN_SAME_SUCC', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_in_succrate',
            field=models.FloatField(blank=True, db_column='ENODEB_IN_SUCCRATE', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_name',
            field=models.ForeignKey(db_column='ENODEB_NAME', on_delete=django.db.models.deletion.CASCADE, to='login.tbcell'),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_out_diff_att',
            field=models.IntegerField(blank=True, db_column='ENODEB_OUT_DIFF_ATT', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_out_diff_succ',
            field=models.IntegerField(blank=True, db_column='ENODEB_OUT_DIFF_SUCC', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_out_same_att',
            field=models.IntegerField(blank=True, db_column='ENODEB_OUT_SAME_ATT', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_out_same_succ',
            field=models.IntegerField(blank=True, db_column='ENODEB_OUT_SAME_SUCC', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_out_succrate',
            field=models.FloatField(blank=True, db_column='ENODEB_OUT_SUCCRATE', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_reset_ue_release',
            field=models.IntegerField(blank=True, db_column='ENODEB_RESET_UE_RELEASE', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_same_succrate',
            field=models.FloatField(blank=True, db_column='ENODEB_SAME_SUCCRATE', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_switch_succrate',
            field=models.FloatField(blank=True, db_column='ENODEB_SWITCH_SUCCRATE', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='erab_att',
            field=models.IntegerField(blank=True, db_column='ERAB_ATT', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='erab_lossrate',
            field=models.FloatField(blank=True, db_column='ERAB_LOSSRATE', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='erab_succ',
            field=models.IntegerField(blank=True, db_column='ERAB_SUCC', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='erab_succrate',
            field=models.FloatField(blank=True, db_column='ERAB_SUCCRATE', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='lossrate',
            field=models.FloatField(blank=True, db_column='LOSSRATE', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='pdcp_down',
            field=models.IntegerField(blank=True, db_column='PDCP_DOWN', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='pdcp_up',
            field=models.IntegerField(blank=True, db_column='PDCP_UP', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='rebuild_enodeb_in_diff_succ',
            field=models.IntegerField(blank=True, db_column='REBUILD_ENODEB_IN_DIFF_SUCC', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='rebuild_enodeb_in_same_succ',
            field=models.IntegerField(blank=True, db_column='REBUILD_ENODEB_IN_SAME_SUCC', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='rebuild_enodeb_out_diff_succ',
            field=models.IntegerField(blank=True, db_column='REBUILD_ENODEB_OUT_DIFF_SUCC', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='rebuild_enodeb_out_same_succ',
            field=models.IntegerField(blank=True, db_column='REBUILD_ENODEB_OUT_SAME_SUCC', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='rpc_establish',
            field=models.IntegerField(blank=True, db_column='RPC_ESTABLISH', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='rpc_rebuild',
            field=models.IntegerField(blank=True, db_column='RPC_REBUILD', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='rpc_rebuildrate',
            field=models.FloatField(blank=True, db_column='RPC_REBUILDRATE', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='rpc_request',
            field=models.IntegerField(blank=True, db_column='RPC_REQUEST', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='rpc_succrate',
            field=models.FloatField(blank=True, db_column='RPC_SUCCRATE', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='sector_switch_erab_ex',
            field=models.IntegerField(blank=True, db_column='SECTOR_SWITCH_ERAB_EX', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='ue_ex_release',
            field=models.IntegerField(blank=True, db_column='UE_EX_RELEASE', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='ue_succ',
            field=models.IntegerField(blank=True, db_column='UE_SUCC', null=True),
        ),
        migrations.AlterField(
            model_name='tbmrodata',
            name='interferingsector',
            field=models.CharField(db_column='InterferingSector', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbmrodata',
            name='servingsector',
            field=models.CharField(db_column='ServingSector', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbmrodata',
            name='timestamp',
            field=models.CharField(db_column='TimeStamp', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbprb',
            name='enodeb_name',
            field=models.ForeignKey(db_column='ENODEB_NAME', on_delete=django.db.models.deletion.CASCADE, to='login.tbcell'),
        ),
    ]
