# Generated by Django 3.1.7 on 2021-05-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210427_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbkpi',
            name='date',
            field=models.DateTimeField(blank=True, db_column='Date', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='enodeb_name',
            field=models.CharField(db_column='ENODEB_NAME', max_length=255),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='pdcp_down',
            field=models.BigIntegerField(blank=True, db_column='PDCP_DOWN', null=True),
        ),
        migrations.AlterField(
            model_name='tbkpi',
            name='pdcp_up',
            field=models.BigIntegerField(blank=True, db_column='PDCP_UP', null=True),
        ),
        migrations.AlterField(
            model_name='tbmrodata',
            name='interferingsector',
            field=models.CharField(db_column='InterferingSector', max_length=30),
        ),
        migrations.AlterField(
            model_name='tbmrodata',
            name='servingsector',
            field=models.CharField(db_column='ServingSector', max_length=30),
        ),
        migrations.AlterField(
            model_name='tbmrodata',
            name='timestamp',
            field=models.CharField(db_column='TimeStamp', max_length=30),
        ),
        migrations.AlterField(
            model_name='tbprb',
            name='date',
            field=models.DateTimeField(db_column='Date'),
        ),
        migrations.AlterField(
            model_name='tbprb',
            name='enodeb_name',
            field=models.CharField(db_column='ENODEB_NAME', max_length=255),
        ),
    ]
