# Generated by Django 3.1.7 on 2021-05-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210525_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbC2Inew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc_sector_id', models.CharField(db_column='NC_SECTOR_ID', max_length=50)),
                ('sc_sector_id', models.CharField(db_column='SC_SECTOR_ID', max_length=50)),
                ('rsrp_avg', models.FloatField(blank=True, db_column='RSRP_AVG', null=True)),
                ('rsrp_std', models.FloatField(blank=True, db_column='RSRP_STD', null=True)),
                ('probility_9', models.FloatField(blank=True, db_column='PROBILITY_9', null=True)),
                ('probility_6', models.FloatField(blank=True, db_column='PROBILITY_6', null=True)),
            ],
            options={
                'db_table': 'tbC2Inew',
                'managed': True,
            },
        ),
    ]
